In [1]:
import numpy as np

#Se decla un nuevo arreglo:

In [2]:
arreglo_numeros = np.array([56,4,24,74,14])
print(arreglo_numeros)

[56  4 24 74 14]


##Matrices de ceros

In [10]:
print(np.zeros((4)))
print(np.zeros((2,2)))
print(np.zeros((3,4,6,)))


[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


##Arreglo de unos

In [11]:
print(np.ones((4)))
print(np.ones((2,2)))
print(np.ones((3,4,6,)))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
