In [4]:
import numpy as np

#Se decla un nuevo arreglo:

In [5]:
arreglo_numeros = np.array([56,4,24,74,14])
print(arreglo_numeros)

[56  4 24 74 14]


##Matrices de ceros

In [6]:
print(np.zeros((4)))
print(np.zeros((2,2)))
print(np.zeros((3,4,6,)))


[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


##Arreglo de unos

In [7]:
print(np.ones((4)))
print(np.ones((2,2)))
print(np.ones((3,4,6,)))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


##Arreglo no inicializado

In [11]:
print(np.empty((4,3)))
print(np.empty((7)))

[[7.15887374e-312 2.81617418e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.75983079e+164]
 [4.96203833e-090 1.51924666e-047 8.26885590e-072]
 [7.71624321e-043 6.48224659e+170 4.93432906e+257]]
[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 3.02875119e-152]


##Arreglo de ceros

In [14]:
print(np.zeros((2,4,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


##Diagonal de unos

In [15]:
print(np.eye(6))
print(np.eye(2))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


## Generación de valores con intervalos

In [18]:
print(np.arange(14))
print(np.arange(45,60))
print(np.arange(0,100,11))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[ 0 11 22 33 44 55 66 77 88 99]


##Obtener las dimensiones de un arreglo

In [19]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

##Cambiar la forma de un arreglo

In [21]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

##Arreglo de unos, con forma de un arreglo dado

In [23]:
print(np.ones_like(np.arange(8).reshape(2,4)))
print(np.ones_like(np.arange(5)))

[[1 1 1 1]
 [1 1 1 1]]
[1 1 1 1 1]


##Arreglos de gran tamaño

In [24]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


##Suma

In [25]:
a = np.array([13,1,42,78])
b = np.array([7,234,43,98])
print(a + b)

[ 20 235  85 176]


##Resta

In [26]:
print(a-b)

[   6 -233   -1  -20]


##Multiplicación

In [27]:
print(a*b)

[  91  234 1806 7644]


##Division

In [28]:
print(a/b)

[1.85714286 0.0042735  0.97674419 0.79591837]


##Operaciones sobre todos los elementos

In [33]:
arregloUno = np.arange(15)
print(arregloUno / 2 )

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7. ]


##Evaluación de expresiones

In [34]:
print(arreglo_diez_ocho < 4)

[ True  True  True  True False False False False False False False False
 False False False False False False]


##Multiplicación dot

In [37]:
A = np.arange(9).reshape(3,3)
B = np.arange(9,18).reshape(3,3)
A.dot(B)
oli = np.arange(20,29).reshape(3,3)
np.dot(A,B,oli)
print(oli)

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


##Operaciones conocidas en los arreglos

In [38]:
print(arregloUno)
print(arregloUno.sum())
print(arregloUno.min())
print(arregloUno.max())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105
0
14


##Sumas sobre los elementos de un arreglo

In [39]:
arregloDos = np.arange(15).reshape(5,3)
print(arregloDos)
print(arregloDos.sum(axis=0)) # Eje X
print(arregloDos.sum(axis=1)) # Eje Y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[30 35 40]
[ 3 12 21 30 39]


#Funciones Universales

##Radianes

In [42]:
angulos = np.array([0, 30, 45, 60, 90])
print(angulos)
angulos_radianes = angulos * np.pi / 180
print(angulos_radianes)
print(np.pi)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
3.141592653589793


##Seno

In [43]:
print(np.sin(angulos))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


##Coseno

In [44]:
print(np.cos(angulos))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


##Tangente

In [45]:
print(np.tan(angulos))

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


##Media

In [46]:
arreglo = np.random.rand(20)*10
print(arreglo)
print(np.mean(arreglo))

[5.60445801 4.90287274 1.50053863 3.98967744 7.28855728 9.74510088
 6.32995602 3.97040868 6.85938242 6.21473063 0.94069084 5.03681165
 4.14076879 5.17086982 8.12015474 9.69463023 1.80020043 2.31478739
 7.6667181  0.5840241 ]
5.093766941887894


##Mediana

In [47]:
print(arreglo)
print(np.median(arreglo))

[5.60445801 4.90287274 1.50053863 3.98967744 7.28855728 9.74510088
 6.32995602 3.97040868 6.85938242 6.21473063 0.94069084 5.03681165
 4.14076879 5.17086982 8.12015474 9.69463023 1.80020043 2.31478739
 7.6667181  0.5840241 ]
5.103840734420642


##Desviación Estándar

In [48]:
print(arreglo)
print(np.std(arreglo))

[5.60445801 4.90287274 1.50053863 3.98967744 7.28855728 9.74510088
 6.32995602 3.97040868 6.85938242 6.21473063 0.94069084 5.03681165
 4.14076879 5.17086982 8.12015474 9.69463023 1.80020043 2.31478739
 7.6667181  0.5840241 ]
2.665184641728105


##Varianza

In [49]:
print(arreglo)
print(np.var(arreglo))

[5.60445801 4.90287274 1.50053863 3.98967744 7.28855728 9.74510088
 6.32995602 3.97040868 6.85938242 6.21473063 0.94069084 5.03681165
 4.14076879 5.17086982 8.12015474 9.69463023 1.80020043 2.31478739
 7.6667181  0.5840241 ]
7.103209174503368


##Slice and dice

In [50]:
arreglo_slice = np.arange(20) ** 2
print(arreglo_slice)
print(arreglo_slice[0])
print(arreglo_slice[0:3])
print(arreglo_slice[-3])
print(arreglo_slice[2:-3])
print(arreglo_slice[-8:-1])
print(arreglo_slice[1:])
print(arreglo_slice[:5])
print(arreglo_slice[2:8])
print(arreglo_slice[2:8:4])
print(arreglo_slice[:10:2])
print(arreglo_slice[::-1])

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]
0
[0 1 4]
289
[  4   9  16  25  36  49  64  81 100 121 144 169 196 225 256]
[144 169 196 225 256 289 324]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
[ 0  1  4  9 16]
[ 4  9 16 25 36 49]
[ 4 36]
[ 0  4 16 36 64]
[361 324 289 256 225 196 169 144 121 100  81  64  49  36  25  16   9   4
   1   0]
