In [4]:
import numpy as np

#Se decla un nuevo arreglo:

In [5]:
arreglo_numeros = np.array([56,4,24,74,14])
print(arreglo_numeros)

[56  4 24 74 14]


##Matrices de ceros

In [6]:
print(np.zeros((4)))
print(np.zeros((2,2)))
print(np.zeros((3,4,6,)))


[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


##Arreglo de unos

In [7]:
print(np.ones((4)))
print(np.ones((2,2)))
print(np.ones((3,4,6,)))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


##Arreglo no inicializado

In [11]:
print(np.empty((4,3)))
print(np.empty((7)))

[[7.15887374e-312 2.81617418e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.75983079e+164]
 [4.96203833e-090 1.51924666e-047 8.26885590e-072]
 [7.71624321e-043 6.48224659e+170 4.93432906e+257]]
[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 3.02875119e-152]


##Arreglo de ceros

In [14]:
print(np.zeros((2,4,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


##Diagonal de unos

In [15]:
print(np.eye(6))
print(np.eye(2))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


## Generación de valores con intervalos

In [18]:
print(np.arange(14))
print(np.arange(45,60))
print(np.arange(0,100,11))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[ 0 11 22 33 44 55 66 77 88 99]


##Obtener las dimensiones de un arreglo

In [19]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

##Cambiar la forma de un arreglo

In [21]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

##Arreglo de unos, con forma de un arreglo dado

In [23]:
print(np.ones_like(np.arange(8).reshape(2,4)))
print(np.ones_like(np.arange(5)))

[[1 1 1 1]
 [1 1 1 1]]
[1 1 1 1 1]


##Arreglos de gran tamaño

In [24]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]
